In [ ]:
pip install pandas sqlalchemy pymysql

Collecting pandas
  Downloading pandas-2.3.2-cp39-cp39-win_amd64.whl (11.3 MB)
     ---------------------------------------- 11.3/11.3 MB 1.5 MB/s eta 0:00:00
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.43-cp39-cp39-win_amd64.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 1.4 MB/s eta 0:00:00
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
     ---------------------------------------- 45.3/45.3 KB 1.1 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\onedrive\desktop\retail_da\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1
  Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
     -------------------------------------- 509.2/509.2 KB 2.1 MB/s eta 0:00:00
Collecting numpy>=1.22.4
  Using cached numpy-2.0.2-cp39-cp39-win_amd64.whl (15.9 MB)
Collecting tzdata>=2022.7
  Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
     -------------------------------------- 347.8/347.8 KB 1.8 MB/s eta 0:00:00
Collecting greenlet>=1
  Downloading greenlet-3.2.4-cp39-cp39-win_amd64.whl (298 kB)
     -------------------------------------- 298.5/298.5 KB 2.3 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\onedrive\desktop\retail_da\.venv\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\admin\onedrive\desktop\retail_da\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: pytz, tzdata, pymysql, numpy, greenlet, sqlalchemy, pandas
Successfully installed greenlet-3.2.4 numpy-2.0.2 pandas-2.3.2 pymysql-1.1.2 pytz-2025.2 sqlalchemy-2.0.43 tzdata-2025.2
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 22.0.4; however, version 25.2 is available.
You should consider upgrading via the 'c:\Users\Admin\OneDrive\Desktop\Retail_DA\.venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('./data/orders.csv')
df

        OrderID  CustomerID   OrderDate ShippingDate     Status  TotalAmount
0             1         831  26-10-2022   28-10-2022    Pending      2570.96
1             2         795  06-05-2023   10-05-2023    Pending       805.98
2             3         207  23-05-2024   24-05-2024  Delivered      3422.74
3             4         908  23-11-2024   24-11-2024  Delivered       106.75
4             5         318  03-12-2024   08-12-2024  Delivered      2341.06
...         ...         ...         ...          ...        ...          ...
149995   149996         484  22-11-2023   29-11-2023  Delivered       112.12
149996   149997         739  30-04-2025   07-05-2025  Delivered      2303.87
149997   149998         513  02-11-2024   06-11-2024    Shipped        59.20
149998   149999         543  26-03-2025   02-04-2025  Delivered      2448.20
149999   150000         898  05-02-2025   09-02-2025  Delivered      2990.22

[150000 rows x 6 columns]

In [ ]:
df.isnull().sum()

OrderID            0
CustomerID         0
OrderDate          0
ShippingDate    7590
Status             0
TotalAmount        0
dtype: int64

In [ ]:
df.to_csv('./data/orders.csv', index=False, na_rep='NULL')

In [ ]:
df.isnull().sum()

OrderID            0
CustomerID         0
OrderDate          0
ShippingDate    7590
Status             0
TotalAmount        0
dtype: int64

In [ ]:
from sqlalchemy import create_engine

In [ ]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://{user}:{pw}@localhost:3306/{db}".format(
    user="root",
    pw="princy2785",
    db="retail_db"
))

In [ ]:
df.to_sql(con=engine, name="orders", index=False, if_exists='replace')

RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods

In [ ]:
df1 = pd.read_csv('./data/order_details.csv')
df1

        OrderDetailID  OrderID  ProductID  Quantity  UnitPrice  Discount
0                   1        1        362         1     359.08      0.24
1                   2        1         74         2     479.09      0.01
2                   3        1        375         4     374.85      0.10
3                   4        2        307         2     424.20      0.05
4                   5        3        116         2     159.54      0.22
...               ...      ...        ...       ...        ...       ...
450992         450993   150000        347         2     395.62      0.20
450993         450994   150000        382         4     425.16      0.19
450994         450995   150000         39         1     383.36      0.16
450995         450996   150000        394         1      51.63      0.05
450996         450997   150000        192         3     215.83      0.06

[450997 rows x 6 columns]

In [ ]:
df1.to_sql(con=engine, name="order_details", index=False, if_exists='replace')

450997

# data science

# 15 - 7 - 2025

In [ ]:
!pip install numpy

Requirement already satisfied: numpy in c:\users\admin\.anaconda\anaconda4\lib\site-packages (1.26.4)

In [ ]:
import numpy as np

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
l=[1,2,3,4,5]

In [ ]:
type(l)

list

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
l=[1 , 1.5 , "mohit"]
l

[1, 1.5, 'mohit']

In [ ]:
arr = np.array([1,1.5,12,34])
arr

array([ 1. ,  1.5, 12. , 34. ])

In [ ]:
arr = np.array([1,1.5,12,34,'mohit'])
arr

array(['1', '1.5', '12', '34', 'mohit'], dtype='<U32')

In [ ]:
arr.dtype

dtype('<U32')

In [ ]:
arr.ndim                       #ndim

1

In [ ]:
arr.shape

(5,)

In [ ]:
arr.size

5

In [ ]:
arr = np.array([[1,2,3,4,5]])
arr

array([[1, 2, 3, 4, 5]])

In [ ]:
arr = np.array([1,2,3,4,5] , ndmin =2)       # ndmin
arr

array([[1, 2, 3, 4, 5]])

In [ ]:
np.__version__

'1.26.4'

In [ ]:
arr.shape

(1, 5)

In [ ]:
arr.size

5

In [ ]:
arr = np.array([1,2,3,4,5])     #1
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.asarray([1,2,3,4,5])    #2
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.asanyarray([1,2,3,4,5])    #3
arr#dekhh

array([1, 2, 3, 4, 5])

In [ ]:
mat=np.matrix([1,2,3])
mat

matrix([[1, 2, 3]])

In [ ]:
mat=np.matrix([[1,2,3]])
mat

matrix([[1, 2, 3]])

In [ ]:
mat

matrix([[1, 2, 3]])

In [ ]:
np.asanyarray(mat)

matrix([[1, 2, 3]])

In [ ]:
np.asanyarray([[1,2,3]])

array([[1, 2, 3]])

shallow copy

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr1=arr

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1[0]=100

In [ ]:
arr1

array([100,   2,   3,   4,   5])

In [ ]:
arr

array([100,   2,   3,   4,   5])

deep copy

In [ ]:
arr

array([100,   2,   3,   4,   5])

In [ ]:
arr2=arr.copy()

In [ ]:
arr2[1]=100
arr2[0]=50

In [ ]:
arr2

array([ 50, 100,   3,   4,   5])

In [ ]:
arr

array([100,   2,   3,   4,   5])

next topics

In [ ]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i,j : (i==j).astype ("int") , (3,3))

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.fromfunction(lambda i,j : (i>=j).astype("int") , (5,5))

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

# 16 - 07 - 2025

In [ ]:
import numpy as np

In [ ]:
l=[i for i in range (1,11)]
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
np.fromiter(l , dtype="int")

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.fromiter(l , dtype="float")

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.fromiter(l,dtype="<U3")

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U3')

In [ ]:
np.fromiter(l,dtype="<U1")

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '1'], dtype='<U1')

In [ ]:
l=[[i+1,i+2] for i in range (1,11)]
l

[[2, 3],
 [3, 4],
 [4, 5],
 [5, 6],
 [6, 7],
 [7, 8],
 [8, 9],
 [9, 10],
 [10, 11],
 [11, 12]]

In [ ]:
np.fromiter(l,dtype=np.dtype((int,2)))

array([[ 2,  3],
       [ 3,  4],
       [ 4,  5],
       [ 5,  6],
       [ 6,  7],
       [ 7,  8],
       [ 8,  9],
       [ 9, 10],
       [10, 11],
       [11, 12]])

In [ ]:
import numpy as np
arr=np.array(
    [
        [[1,2,3],
         [4,5,6]],

        [[1,2,3],
         [4,5,6]],

        [[1,2,3],
         [4,5,6]],

        [[1,2,3],
         [4,5,6]],

                ]
                )
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
arr.shape

(4, 2, 3)

In [ ]:
l=[[[i+1,i+2,i+3] for i in range (1,3)]
  for j in range (0,4)] # or (4)
l

[[[2, 3, 4], [3, 4, 5]],
 [[2, 3, 4], [3, 4, 5]],
 [[2, 3, 4], [3, 4, 5]],
 [[2, 3, 4], [3, 4, 5]]]

In [ ]:
np.fromiter(l,dtype=np.dtype((int,(2,3))))

array([[[2, 3, 4],
        [3, 4, 5]],

       [[2, 3, 4],
        [3, 4, 5]],

       [[2, 3, 4],
        [3, 4, 5]],

       [[2, 3, 4],
        [3, 4, 5]]])

In [ ]:
#(2,5,3)
l=[ [[i+1,i+2,i+3] for i in range (5)] 
   for j in range (2)]
l

[[[1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6], [5, 6, 7]],
 [[1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6], [5, 6, 7]]]

In [ ]:
arr=np.fromiter(l,dtype=np.dtype((int,(5,3))))
arr

array([[[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6],
        [5, 6, 7]],

       [[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6],
        [5, 6, 7]]])

In [ ]:
arr.shape

(2, 5, 3)

In [ ]:
for i in range (10):
    print(i)

0
1
2
3
4
5
6
7
8
9

In [ ]:
for i in range (1,10,0.5):
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27272727,
        7.36363636,  7.45454545,  7.54545455,  7.63636364,  7.72727273,
        7.81818182,  7.90909091,  8.        ,  8.09090909,  8.18181818,
        8.27272727,  8.36363636,  8.45454545,  8.54545455,  8.63636364,
        8.72727273,  8.81818182,  8.90909091,  9.        ,  9.09090909,
        9.18181818,  9.27272727,  9.36363636,  9.45454545,  9.54545455,
        9.63636364,  9.72727273,  9.81818182,  9.90909091, 10.        ])

In [ ]:
np.linspace(1,10,1000)

array([ 1.        ,  1.00900901,  1.01801802,  1.02702703,  1.03603604,
        1.04504505,  1.05405405,  1.06306306,  1.07207207,  1.08108108,
        1.09009009,  1.0990991 ,  1.10810811,  1.11711712,  1.12612613,
        1.13513514,  1.14414414,  1.15315315,  1.16216216,  1.17117117,
        1.18018018,  1.18918919,  1.1981982 ,  1.20720721,  1.21621622,
        1.22522523,  1.23423423,  1.24324324,  1.25225225,  1.26126126,
        1.27027027,  1.27927928,  1.28828829,  1.2972973 ,  1.30630631,
        1.31531532,  1.32432432,  1.33333333,  1.34234234,  1.35135135,
        1.36036036,  1.36936937,  1.37837838,  1.38738739,  1.3963964 ,
        1.40540541,  1.41441441,  1.42342342,  1.43243243,  1.44144144,
        1.45045045,  1.45945946,  1.46846847,  1.47747748,  1.48648649,
        1.4954955 ,  1.5045045 ,  1.51351351,  1.52252252,  1.53153153,
        1.54054054,  1.54954955,  1.55855856,  1.56756757,  1.57657658,
        1.58558559,  1.59459459,  1.6036036 ,  1.61261261,  1.62162162,
        1.63063063,  1.63963964,  1.64864865,  1.65765766,  1.66666667,
        1.67567568,  1.68468468,  1.69369369,  1.7027027 ,  1.71171171,
        1.72072072,  1.72972973,  1.73873874,  1.74774775,  1.75675676,
        1.76576577,  1.77477477,  1.78378378,  1.79279279,  1.8018018 ,
        1.81081081,  1.81981982,  1.82882883,  1.83783784,  1.84684685,
        1.85585586,  1.86486486,  1.87387387,  1.88288288,  1.89189189,
        1.9009009 ,  1.90990991,  1.91891892,  1.92792793,  1.93693694,
        1.94594595,  1.95495495,  1.96396396,  1.97297297,  1.98198198,
        1.99099099,  2.        ,  2.00900901,  2.01801802,  2.02702703,
        2.03603604,  2.04504505,  2.05405405,  2.06306306,  2.07207207,
        2.08108108,  2.09009009,  2.0990991 ,  2.10810811,  2.11711712,
        2.12612613,  2.13513514,  2.14414414,  2.15315315,  2.16216216,
        2.17117117,  2.18018018,  2.18918919,  2.1981982 ,  2.20720721,
        2.21621622,  2.22522523,  2.23423423,  2.24324324,  2.25225225,
        2.26126126,  2.27027027,  2.27927928,  2.28828829,  2.2972973 ,
        2.30630631,  2.31531532,  2.32432432,  2.33333333,  2.34234234,
        2.35135135,  2.36036036,  2.36936937,  2.37837838,  2.38738739,
        2.3963964 ,  2.40540541,  2.41441441,  2.42342342,  2.43243243,
        2.44144144,  2.45045045,  2.45945946,  2.46846847,  2.47747748,
        2.48648649,  2.4954955 ,  2.5045045 ,  2.51351351,  2.52252252,
        2.53153153,  2.54054054,  2.54954955,  2.55855856,  2.56756757,
        2.57657658,  2.58558559,  2.59459459,  2.6036036 ,  2.61261261,
        2.62162162,  2.63063063,  2.63963964,  2.64864865,  2.65765766,
        2.66666667,  2.67567568,  2.68468468,  2.69369369,  2.7027027 ,
        2.71171171,  2.72072072,  2.72972973,  2.73873874,  2.74774775,
        2.75675676,  2.76576577,  2.77477477,  2.78378378,  2.79279279,
        2.8018018 ,  2.81081081,  2.81981982,  2.82882883,  2.83783784,
        2.84684685,  2.85585586,  2.86486486,  2.87387387,  2.88288288,
        2.89189189,  2.9009009 ,  2.90990991,  2.91891892,  2.92792793,
        2.93693694,  2.94594595,  2.95495495,  2.96396396,  2.97297297,
        2.98198198,  2.99099099,  3.        ,  3.00900901,  3.01801802,
        3.02702703,  3.03603604,  3.04504505,  3.05405405,  3.06306306,
        3.07207207,  3.08108108,  3.09009009,  3.0990991 ,  3.10810811,
        3.11711712,  3.12612613,  3.13513514,  3.14414414,  3.15315315,
        3.16216216,  3.17117117,  3.18018018,  3.18918919,  3.1981982 ,
        3.20720721,  3.21621622,  3.22522523,  3.23423423,  3.24324324,
        3.25225225,  3.26126126,  3.27027027,  3.27927928,  3.28828829,
        3.2972973 ,  3.30630631,  3.31531532,  3.32432432,  3.33333333,
        3.34234234,  3.35135135,  3.36036036,  3.36936937,  3.37837838,
        3.38738739,  3.3963964 ,  3.40540541,  3.41441441,  3.42342342,
        3.43243243,  3.44144144,  3.45045045,  3.45945946,  3.46846847,
        3.47747748,  3.48648649,  3.4954955 ,  3.5045045 ,  3.51351351,
        3.52252252,  3.53153153,  3.54054054,  3.54954955,  3.55855856,
        3.56756757,  3.57657658,  3.58558559,  3.59459459,  3.6036036 ,
        3.61261261,  3.62162162,  3.63063063,  3.63963964,  3.64864865,
        3.65765766,  3.66666667,  3.67567568,  3.68468468,  3.69369369,
        3.7027027 ,  3.71171171,  3.72072072,  3.72972973,  3.73873874,
        3.74774775,  3.75675676,  3.76576577,  3.77477477,  3.78378378,
        3.79279279,  3.8018018 ,  3.81081081,  3.81981982,  3.82882883,
        3.83783784,  3.84684685,  3.85585586,  3.86486486,  3.87387387,
        3.88288288,  3.89189189,  3.9009009 ,  3.90990991,  3.91891892,
        3.92792793,  3.93693694,  3.94594595,  3.95495495,  3.96396396,
        3.97297297,  3.98198198,  3.99099099,  4.        ,  4.00900901,
        4.01801802,  4.02702703,  4.03603604,  4.04504505,  4.05405405,
        4.06306306,  4.07207207,  4.08108108,  4.09009009,  4.0990991 ,
        4.10810811,  4.11711712,  4.12612613,  4.13513514,  4.14414414,
        4.15315315,  4.16216216,  4.17117117,  4.18018018,  4.18918919,
        4.1981982 ,  4.20720721,  4.21621622,  4.22522523,  4.23423423,
        4.24324324,  4.25225225,  4.26126126,  4.27027027,  4.27927928,
        4.28828829,  4.2972973 ,  4.30630631,  4.31531532,  4.32432432,
        4.33333333,  4.34234234,  4.35135135,  4.36036036,  4.36936937,
        4.37837838,  4.38738739,  4.3963964 ,  4.40540541,  4.41441441,
        4.42342342,  4.43243243,  4.44144144,  4.45045045,  4.45945946,
        4.46846847,  4.47747748,  4.48648649,  4.4954955 ,  4.5045045 ,
        4.51351351,  4.52252252,  4.53153153,  4.54054054,  4.54954955,
        4.55855856,  4.56756757,  4.57657658,  4.58558559,  4.59459459,
        4.6036036 ,  4.61261261,  4.62162162,  4.63063063,  4.63963964,
        4.64864865,  4.65765766,  4.66666667,  4.67567568,  4.68468468,
        4.69369369,  4.7027027 ,  4.71171171,  4.72072072,  4.72972973,
        4.73873874,  4.74774775,  4.75675676,  4.76576577,  4.77477477,
        4.78378378,  4.79279279,  4.8018018 ,  4.81081081,  4.81981982,
        4.82882883,  4.83783784,  4.84684685,  4.85585586,  4.86486486,
        4.87387387,  4.88288288,  4.89189189,  4.9009009 ,  4.90990991,
        4.91891892,  4.92792793,  4.93693694,  4.94594595,  4.95495495,
        4.96396396,  4.97297297,  4.98198198,  4.99099099,  5.        ,
        5.00900901,  5.01801802,  5.02702703,  5.03603604,  5.04504505,
        5.05405405,  5.06306306,  5.07207207,  5.08108108,  5.09009009,
        5.0990991 ,  5.10810811,  5.11711712,  5.12612613,  5.13513514,
        5.14414414,  5.15315315,  5.16216216,  5.17117117,  5.18018018,
        5.18918919,  5.1981982 ,  5.20720721,  5.21621622,  5.22522523,
        5.23423423,  5.24324324,  5.25225225,  5.26126126,  5.27027027,
        5.27927928,  5.28828829,  5.2972973 ,  5.30630631,  5.31531532,
        5.32432432,  5.33333333,  5.34234234,  5.35135135,  5.36036036,
        5.36936937,  5.37837838,  5.38738739,  5.3963964 ,  5.40540541,
        5.41441441,  5.42342342,  5.43243243,  5.44144144,  5.45045045,
        5.45945946,  5.46846847,  5.47747748,  5.48648649,  5.4954955 ,
        5.5045045 ,  5.51351351,  5.52252252,  5.53153153,  5.54054054,
        5.54954955,  5.55855856,  5.56756757,  5.57657658,  5.58558559,
        5.59459459,  5.6036036 ,  5.61261261,  5.62162162,  5.63063063,
        5.63963964,  5.64864865,  5.65765766,  5.66666667,  5.67567568,
        5.68468468,  5.69369369,  5.7027027 ,  5.71171171,  5.72072072,
        5.72972973,  5.73873874,  5.74774775,  5.75675676,  5.76576577,
        5.77477477,  5.78378378,  5.79279279,  5.8018018 ,  5.81081081,
        5.81981982,  5.82882883,  5.83783784,  5.84684685,  5.85585586,
        5.86486486,  5.87387387,  5.88288288,  5.89189189,  5.9009009 ,
        5.90990991,  5.91891892,  5.92792793,  5.93693694,  5.94594595,
        5.95495495,  5.96396396,  5.97297297,  5.98198198,  5.99099099,
        6.        ,  6.00900901,  6.01801802,  6.02702703,  6.03603604,
        6.04504505,  6.05405405,  6.06306306,  6.07207207,  6.08108108,
        6.09009009,  6.0990991 ,  6.10810811,  6.11711712,  6.12612613,
        6.13513514,  6.14414414,  6.15315315,  6.16216216,  6.17117117,
        6.18018018,  6.18918919,  6.1981982 ,  6.20720721,  6.21621622,
        6.22522523,  6.23423423,  6.24324324,  6.25225225,  6.26126126,
        6.27027027,  6.27927928,  6.28828829,  6.2972973 ,  6.30630631,
        6.31531532,  6.32432432,  6.33333333,  6.34234234,  6.35135135,
        6.36036036,  6.36936937,  6.37837838,  6.38738739,  6.3963964 ,
        6.40540541,  6.41441441,  6.42342342,  6.43243243,  6.44144144,
        6.45045045,  6.45945946,  6.46846847,  6.47747748,  6.48648649,
        6.4954955 ,  6.5045045 ,  6.51351351,  6.52252252,  6.53153153,
        6.54054054,  6.54954955,  6.55855856,  6.56756757,  6.57657658,
        6.58558559,  6.59459459,  6.6036036 ,  6.61261261,  6.62162162,
        6.63063063,  6.63963964,  6.64864865,  6.65765766,  6.66666667,
        6.67567568,  6.68468468,  6.69369369,  6.7027027 ,  6.71171171,
        6.72072072,  6.72972973,  6.73873874,  6.74774775,  6.75675676,
        6.76576577,  6.77477477,  6.78378378,  6.79279279,  6.8018018 ,
        6.81081081,  6.81981982,  6.82882883,  6.83783784,  6.84684685,
        6.85585586,  6.86486486,  6.87387387,  6.88288288,  6.89189189,
        6.9009009 ,  6.90990991,  6.91891892,  6.92792793,  6.93693694,
        6.94594595,  6.95495495,  6.96396396,  6.97297297,  6.98198198,
        6.99099099,  7.        ,  7.00900901,  7.01801802,  7.02702703,
        7.03603604,  7.04504505,  7.05405405,  7.06306306,  7.07207207,
        7.08108108,  7.09009009,  7.0990991 ,  7.10810811,  7.11711712,
        7.12612613,  7.13513514,  7.14414414,  7.15315315,  7.16216216,
        7.17117117,  7.18018018,  7.18918919,  7.1981982 ,  7.20720721,
        7.21621622,  7.22522523,  7.23423423,  7.24324324,  7.25225225,
        7.26126126,  7.27027027,  7.27927928,  7.28828829,  7.2972973 ,
        7.30630631,  7.31531532,  7.32432432,  7.33333333,  7.34234234,
        7.35135135,  7.36036036,  7.36936937,  7.37837838,  7.38738739,
        7.3963964 ,  7.40540541,  7.41441441,  7.42342342,  7.43243243,
        7.44144144,  7.45045045,  7.45945946,  7.46846847,  7.47747748,
        7.48648649,  7.4954955 ,  7.5045045 ,  7.51351351,  7.52252252,
        7.53153153,  7.54054054,  7.54954955,  7.55855856,  7.56756757,
        7.57657658,  7.58558559,  7.59459459,  7.6036036 ,  7.61261261,
        7.62162162,  7.63063063,  7.63963964,  7.64864865,  7.65765766,
        7.66666667,  7.67567568,  7.68468468,  7.69369369,  7.7027027 ,
        7.71171171,  7.72072072,  7.72972973,  7.73873874,  7.74774775,
        7.75675676,  7.76576577,  7.77477477,  7.78378378,  7.79279279,
        7.8018018 ,  7.81081081,  7.81981982,  7.82882883,  7.83783784,
        7.84684685,  7.85585586,  7.86486486,  7.87387387,  7.88288288,
        7.89189189,  7.9009009 ,  7.90990991,  7.91891892,  7.92792793,
        7.93693694,  7.94594595,  7.95495495,  7.96396396,  7.97297297,
        7.98198198,  7.99099099,  8.        ,  8.00900901,  8.01801802,
        8.02702703,  8.03603604,  8.04504505,  8.05405405,  8.06306306,
        8.07207207,  8.08108108,  8.09009009,  8.0990991 ,  8.10810811,
        8.11711712,  8.12612613,  8.13513514,  8.14414414,  8.15315315,
        8.16216216,  8.17117117,  8.18018018,  8.18918919,  8.1981982 ,
        8.20720721,  8.21621622,  8.22522523,  8.23423423,  8.24324324,
        8.25225225,  8.26126126,  8.27027027,  8.27927928,  8.28828829,
        8.2972973 ,  8.30630631,  8.31531532,  8.32432432,  8.33333333,
        8.34234234,  8.35135135,  8.36036036,  8.36936937,  8.37837838,
        8.38738739,  8.3963964 ,  8.40540541,  8.41441441,  8.42342342,
        8.43243243,  8.44144144,  8.45045045,  8.45945946,  8.46846847,
        8.47747748,  8.48648649,  8.4954955 ,  8.5045045 ,  8.51351351,
        8.52252252,  8.53153153,  8.54054054,  8.54954955,  8.55855856,
        8.56756757,  8.57657658,  8.58558559,  8.59459459,  8.6036036 ,
        8.61261261,  8.62162162,  8.63063063,  8.63963964,  8.64864865,
        8.65765766,  8.66666667,  8.67567568,  8.68468468,  8.69369369,
        8.7027027 ,  8.71171171,  8.72072072,  8.72972973,  8.73873874,
        8.74774775,  8.75675676,  8.76576577,  8.77477477,  8.78378378,
        8.79279279,  8.8018018 ,  8.81081081,  8.81981982,  8.82882883,
        8.83783784,  8.84684685,  8.85585586,  8.86486486,  8.87387387,
        8.88288288,  8.89189189,  8.9009009 ,  8.90990991,  8.91891892,
        8.92792793,  8.93693694,  8.94594595,  8.95495495,  8.96396396,
        8.97297297,  8.98198198,  8.99099099,  9.        ,  9.00900901,
        9.01801802,  9.02702703,  9.03603604,  9.04504505,  9.05405405,
        9.06306306,  9.07207207,  9.08108108,  9.09009009,  9.0990991 ,
        9.10810811,  9.11711712,  9.12612613,  9.13513514,  9.14414414,
        9.15315315,  9.16216216,  9.17117117,  9.18018018,  9.18918919,
        9.1981982 ,  9.20720721,  9.21621622,  9.22522523,  9.23423423,
        9.24324324,  9.25225225,  9.26126126,  9.27027027,  9.27927928,
        9.28828829,  9.2972973 ,  9.30630631,  9.31531532,  9.32432432,
        9.33333333,  9.34234234,  9.35135135,  9.36036036,  9.36936937,
        9.37837838,  9.38738739,  9.3963964 ,  9.40540541,  9.41441441,
        9.42342342,  9.43243243,  9.44144144,  9.45045045,  9.45945946,
        9.46846847,  9.47747748,  9.48648649,  9.4954955 ,  9.5045045 ,
        9.51351351,  9.52252252,  9.53153153,  9.54054054,  9.54954955,
        9.55855856,  9.56756757,  9.57657658,  9.58558559,  9.59459459,
        9.6036036 ,  9.61261261,  9.62162162,  9.63063063,  9.63963964,
        9.64864865,  9.65765766,  9.66666667,  9.67567568,  9.68468468,
        9.69369369,  9.7027027 ,  9.71171171,  9.72072072,  9.72972973,
        9.73873874,  9.74774775,  9.75675676,  9.76576577,  9.77477477,
        9.78378378,  9.79279279,  9.8018018 ,  9.81081081,  9.81981982,
        9.82882883,  9.83783784,  9.84684685,  9.85585586,  9.86486486,
        9.87387387,  9.88288288,  9.89189189,  9.9009009 ,  9.90990991,
        9.91891892,  9.92792793,  9.93693694,  9.94594595,  9.95495495,
        9.96396396,  9.97297297,  9.98198198,  9.99099099, 10.        ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones((2,5,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
import random
random.random()

0.5033054299969256

In [ ]:
import random
random.randint(1,11)

9

In [ ]:
np.random.rand()

0.9167419564357692

In [ ]:
np.random.rand(10)

array([0.18058207, 0.47808772, 0.18462002, 0.71136439, 0.42856074,
       0.16468926, 0.7262313 , 0.78220005, 0.21202904, 0.36510312])

In [ ]:
np.random.rand(5,5)

array([[0.56990031, 0.83942247, 0.61830622, 0.8034673 , 0.17254618],
       [0.92680462, 0.55521915, 0.67661666, 0.59419459, 0.42939477],
       [0.86795354, 0.3690236 , 0.09041163, 0.74128962, 0.3059277 ],
       [0.12512869, 0.09679097, 0.68700765, 0.16795186, 0.0622261 ],
       [0.41645422, 0.27023569, 0.50330496, 0.85672289, 0.20330728]])

In [ ]:
np.random.rand(5,5,2)      #rand

array([[[0.04093479, 0.74336493],
        [0.05199337, 0.36721317],
        [0.67815727, 0.74594842],
        [0.31681339, 0.51032877],
        [0.1655178 , 0.5123953 ]],

       [[0.90816969, 0.78805627],
        [0.01160933, 0.69271906],
        [0.41951167, 0.58395589],
        [0.7045018 , 0.51200971],
        [0.92387132, 0.8153022 ]],

       [[0.37138869, 0.99187032],
        [0.45472462, 0.85466258],
        [0.61192548, 0.01884374],
        [0.02283042, 0.17567253],
        [0.39153155, 0.22794231]],

       [[0.78237374, 0.64451945],
        [0.38042241, 0.60985659],
        [0.42368558, 0.76799511],
        [0.14664772, 0.67284596],
        [0.57151623, 0.13784557]],

       [[0.40990805, 0.09594541],
        [0.25669206, 0.17277326],
        [0.20171771, 0.46367908],
        [0.44335752, 0.58059349],
        [0.01819071, 0.63272526]]])

In [ ]:
arr=np.random.randn(3,3)    # randn
arr

array([[-0.95458217, -0.42095526, -1.87285776],
       [ 1.51492326,  0.61937709, -2.55264071],
       [-1.18933321, -1.29129745, -0.03595406]])

In [ ]:
arr.mean()

-0.6870355863587849

In [ ]:
arr.std()

1.1844227799757985

In [ ]:
arr=np.random.randint(1,100,50)    #randint
arr

array([51, 93,  9, 73, 84,  2,  6, 70,  4, 53, 97, 34,  7, 59, 69, 28, 21,
       40, 15,  5, 26, 73, 11, 53, 97, 94, 98, 22, 47, 67, 95, 25, 99, 66,
       35,  5, 79,  1, 94, 97, 47, 84, 82, 34, 30,  2,  6, 46, 55, 99])

In [ ]:
arr>=60

array([False,  True, False,  True,  True, False, False,  True, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False,  True, False, False,  True,  True,  True,
       False, False,  True,  True, False,  True,  True, False, False,
        True, False,  True,  True, False,  True,  True, False, False,
       False, False, False, False,  True])

In [ ]:
arr[arr>=60]

array([93, 73, 84, 70, 97, 69, 73, 97, 94, 98, 67, 95, 99, 66, 79, 94, 97,
       84, 82, 99])

In [ ]:
len(arr[arr>=60])

20

In [ ]:
arr=np.random.uniform(1,100,50)
arr

array([98.11309377, 96.00906691, 38.31673753, 94.12189942, 68.56475002,
       58.84950268,  4.11555776, 55.67174799, 75.90558263, 67.51975699,
       16.20962176, 15.70427948, 18.25399247, 36.76778522, 17.34486606,
       56.57609694, 95.97729475,  1.95961168, 53.19555304, 28.03063783,
       19.68452594, 74.00848436, 87.93704368, 89.59300238, 71.10202325,
       39.83024399, 92.55283618, 98.16062544, 11.3010849 , 62.72888064,
       10.48149381,  8.9758297 , 34.52152344, 26.05154243, 35.19568965,
        8.91474889, 58.97414837, 64.83655251, 19.63009727, 55.52027966,
       96.90828291, 18.90634534, 36.39681311, 11.43197086,  2.79815183,
       19.64385847, 55.43448542,  7.50928804, 18.29231354, 19.89299976])

In [ ]:
arr=np.random.randint(1,100,(1000,5))    
arr

array([[77, 66, 12, 73, 22],
       [63, 26, 63, 46, 28],
       [79,  5, 86, 30, 59],
       ...,
       [24, 64, 63, 99,  3],
       [45, 43, 52, 55, 36],
       [93, 30, 79, 36, 47]])

In [ ]:
import  pandas as pd
df = pd.DataFrame(arr)    # line means
df

      0   1   2   3   4
0    77  66  12  73  22
1    63  26  63  46  28
2    79   5  86  30  59
3    65  50  10  20  62
4    75  22  30  52   4
..   ..  ..  ..  ..  ..
995  36  62  83  97  23
996  30  29  85  69  85
997  24  64  63  99   3
998  45  43  52  55  36
999  93  30  79  36  47

[1000 rows x 5 columns]

In [ ]:
df=pd.DataFrame(arr,columns=["maths","science" , "sst" , "cs" , "english"])
df

     maths  science  sst  cs  english
0       77       66   12  73       22
1       63       26   63  46       28
2       79        5   86  30       59
3       65       50   10  20       62
4       75       22   30  52        4
..     ...      ...  ...  ..      ...
995     36       62   83  97       23
996     30       29   85  69       85
997     24       64   63  99        3
998     45       43   52  55       36
999     93       30   79  36       47

[1000 rows x 5 columns]

In [ ]:
df.to_csv("report_card.csv")    # means csv

In [ ]:
df.to_csv("report_card.csv",index=False) # index nhi hta
df

     maths  science  sst  cs  english
0       77       66   12  73       22
1       63       26   63  46       28
2       79        5   86  30       59
3       65       50   10  20       62
4       75       22   30  52        4
..     ...      ...  ...  ..      ...
995     36       62   83  97       23
996     30       29   85  69       85
997     24       64   63  99        3
998     45       43   52  55       36
999     93       30   79  36       47

[1000 rows x 5 columns]

In [ ]:
arr=np.random.randint(1,5,(5,5))
arr

array([[2, 1, 3, 1, 1],
       [4, 1, 3, 4, 3],
       [4, 4, 4, 3, 3],
       [1, 2, 1, 1, 4],
       [1, 2, 3, 1, 4]])

In [ ]:
arr.size

25

In [ ]:
arr.shape

(5, 5)

In [ ]:
arr.reshape(1,25)

array([[2, 1, 3, 1, 1, 4, 1, 3, 4, 3, 4, 4, 4, 3, 3, 1, 2, 1, 1, 4, 1, 2,
        3, 1, 4]])

In [ ]:
arr=np.random.randint(1,5,(5,2))
arr

array([[4, 2],
       [1, 4],
       [1, 2],
       [2, 4],
       [3, 4]])

In [ ]:
arr.reshape(2,5)

array([[4, 2, 1, 4, 1],
       [2, 2, 4, 3, 4]])

In [ ]:
arr=np.random.randint(1,5,(5,4))
arr

array([[3, 2, 4, 2],
       [2, 3, 3, 2],
       [1, 4, 3, 1],
       [1, 1, 4, 3],
       [2, 3, 3, 3]])

In [ ]:
arr.reshape(2,-1)

array([[3, 2, 4, 2, 2, 3, 3, 2, 1, 4],
       [3, 1, 1, 1, 4, 3, 2, 3, 3, 3]])

In [ ]:
arr.reshape(-1,5)

array([[3, 2, 4, 2, 2],
       [3, 3, 2, 1, 4],
       [3, 1, 1, 1, 4],
       [3, 2, 3, 3, 3]])

In [ ]:
arr=np.random.randint(1,5,(5,2,3))
arr

array([[[2, 1, 2],
        [1, 4, 4]],

       [[2, 1, 1],
        [2, 4, 2]],

       [[2, 2, 4],
        [3, 4, 4]],

       [[4, 3, 2],
        [1, 1, 1]],

       [[1, 3, 2],
        [4, 4, 1]]])

In [ ]:
arr.shape

(5, 2, 3)

In [ ]:
arr.size

30

In [ ]:
arr.reshape(6,5)

array([[2, 1, 2, 1, 4],
       [4, 2, 1, 1, 2],
       [4, 2, 2, 2, 4],
       [3, 4, 4, 4, 3],
       [2, 1, 1, 1, 1],
       [3, 2, 4, 4, 1]])

In [ ]:
arr.flatten()

array([2, 1, 2, 1, 4, 4, 2, 1, 1, 2, 4, 2, 2, 2, 4, 3, 4, 4, 4, 3, 2, 1,
       1, 1, 1, 3, 2, 4, 4, 1])

In [ ]:
arr.reshape(-1)

array([2, 1, 2, 1, 4, 4, 2, 1, 1, 2, 4, 2, 2, 2, 4, 3, 4, 4, 4, 3, 2, 1,
       1, 1, 1, 3, 2, 4, 4, 1])

In [ ]:
arr.reshape(3,2,5)

array([[[2, 1, 2, 1, 4],
        [4, 2, 1, 1, 2]],

       [[4, 2, 2, 2, 4],
        [3, 4, 4, 4, 3]],

       [[2, 1, 1, 1, 1],
        [3, 2, 4, 4, 1]]])

In [ ]:
arr.T    # kese hua

array([[[2, 2, 2, 4, 1],
        [1, 2, 3, 1, 4]],

       [[1, 1, 2, 3, 3],
        [4, 4, 4, 1, 4]],

       [[2, 1, 4, 2, 2],
        [4, 2, 4, 1, 1]]])

In [ ]:
arr.transpose()

array([[[2, 2, 2, 4, 1],
        [1, 2, 3, 1, 4]],

       [[1, 1, 2, 3, 3],
        [4, 4, 4, 1, 4]],

       [[2, 1, 4, 2, 2],
        [4, 2, 4, 1, 1]]])

# 17 - 07 - 2025

In [ ]:
import numpy as np

In [ ]:
arr=np.random.randint(1,100,(5,5))
arr

array([[62, 49, 14, 31,  1],
       [11, 49, 70, 46, 12],
       [81,  3, 17, 46, 10],
       [97, 90, 53, 86, 30],
       [70, 89, 18, 41, 59]])

In [ ]:
arr[1][1]

49

In [ ]:
arr[4][4]

59

In [ ]:
arr[-1][-1]

59

In [ ]:
arr[-5][-5]

62

In [ ]:
arr[-1][-5]

70

In [ ]:
arr

array([[62, 49, 14, 31,  1],
       [11, 49, 70, 46, 12],
       [81,  3, 17, 46, 10],
       [97, 90, 53, 86, 30],
       [70, 89, 18, 41, 59]])

In [ ]:
arr[:,[1]]

array([[49],
       [49],
       [ 3],
       [90],
       [89]])

In [ ]:
arr[:,[1,3]]

array([[49, 31],
       [49, 46],
       [ 3, 46],
       [90, 86],
       [89, 41]])

In [ ]:
arr

array([[62, 49, 14, 31,  1],
       [11, 49, 70, 46, 12],
       [81,  3, 17, 46, 10],
       [97, 90, 53, 86, 30],
       [70, 89, 18, 41, 59]])

In [ ]:
arr[[1],:]

array([[11, 49, 70, 46, 12]])

In [ ]:
arr[[1,4],:]

array([[11, 49, 70, 46, 12],
       [70, 89, 18, 41, 59]])

In [ ]:
arr[[-4,-1],:]

array([[11, 49, 70, 46, 12],
       [70, 89, 18, 41, 59]])

In [ ]:
arr

array([[62, 49, 14, 31,  1],
       [11, 49, 70, 46, 12],
       [81,  3, 17, 46, 10],
       [97, 90, 53, 86, 30],
       [70, 89, 18, 41, 59]])

In [ ]:
# (2nd row vala)49 , 46 , 3 , 46
arr[1:3,1:4:2]                    #means 1:4:2

array([[49, 46],
       [ 3, 46]])

In [ ]:
arr[1:3]

array([[11, 49, 70, 46, 12],
       [81,  3, 17, 46, 10]])

In [ ]:
arr[1:3,[1,3]]

array([[49, 46],
       [ 3, 46]])

In [ ]:
arr

array([[62, 49, 14, 31,  1],
       [11, 49, 70, 46, 12],
       [81,  3, 17, 46, 10],
       [97, 90, 53, 86, 30],
       [70, 89, 18, 41, 59]])

In [ ]:
arr.shape

(5, 5)

In [ ]:
len(arr)             # 5 kese

5

In [ ]:
arr[::arr.shape[0]-1,::arr.shape[1]-1]                  #means

array([[62,  1],
       [70, 59]])

In [ ]:
arr[::arr.shape[0]-1,::arr.shape[1]-1]=0     
arr

array([[ 0, 49, 14, 31,  0],
       [11, 49, 70, 46, 12],
       [81,  3, 17, 46, 10],
       [97, 90, 53, 86, 30],
       [ 0, 89, 18, 41,  0]])

In [ ]:
arr=np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr[:,0]=0
arr[:,-1]=0
arr[0,:]=0
arr[-1,:]=0
arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr1=np.random.randint(1,3,(3,3))
arr1
arr2=np.random.randint(1,3,(3,3))
arr2

array([[2, 2, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [ ]:
arr1

array([[2, 1, 2],
       [1, 1, 1],
       [2, 2, 2]])

In [ ]:
arr2

array([[2, 2, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [ ]:
arr1-arr2

array([[ 0, -1,  0],
       [-1, -1,  0],
       [ 1,  1,  1]])

In [ ]:
arr1+arr2

array([[4, 3, 4],
       [3, 3, 2],
       [3, 3, 3]])

In [ ]:
arr1*arr2

array([[4, 2, 4],
       [2, 2, 1],
       [2, 2, 2]])

In [ ]:
arr1/arr2

array([[1. , 0.5, 1. ],
       [0.5, 0.5, 1. ],
       [2. , 2. , 2. ]])

In [ ]:
arr1/0

C:\Users\Admin\AppData\Local\Temp\ipykernel_23116\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0

array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
arr1**arr2

array([[4, 1, 4],
       [1, 1, 1],
       [2, 2, 2]])

In [ ]:
arr1>arr2

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [ ]:
arr1

array([[2, 1, 2],
       [1, 1, 1],
       [2, 2, 2]])

In [ ]:
arr2

array([[2, 2, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [ ]:
arr1.shape

(3, 3)

In [ ]:
arr2.shape

(3, 3)

In [ ]:
arr1@arr2                  #matrix multiplication

array([[ 8,  8,  7],
       [ 5,  5,  4],
       [10, 10,  8]])

In [ ]:
np.dot(arr1,arr2)

array([[ 8,  8,  7],
       [ 5,  5,  4],
       [10, 10,  8]])

In [ ]:
np.matmul(arr1,arr2)

array([[ 8,  8,  7],
       [ 5,  5,  4],
       [10, 10,  8]])

In [ ]:
arr1=np.random.randint(1,3,(5,3))
arr1
arr2=np.random.randint(1,3,(3,2))
arr2

array([[2, 1],
       [1, 2],
       [1, 2]])

In [ ]:
arr1

array([[1, 1, 2],
       [2, 2, 1],
       [1, 1, 1],
       [2, 2, 2],
       [1, 1, 2]])

In [ ]:
arr2

array([[2, 1],
       [1, 2],
       [1, 2]])

In [ ]:
arr1.shape

(5, 3)

In [ ]:
arr2.shape

(3, 2)

In [ ]:
arr1@arr2

array([[ 5,  7],
       [ 7,  8],
       [ 4,  5],
       [ 8, 10],
       [ 5,  7]])

In [ ]:
arr2=np.random.randint(1,100,(5,3))
arr2
arr1=np.random.randint(1,100,(5,3))
arr1

array([[31, 44, 77],
       [13, 10, 72],
       [ 9, 46, 32],
       [77, 81, 10],
       [83, 94,  4]])

In [ ]:
arr1

array([[31, 44, 77],
       [13, 10, 72],
       [ 9, 46, 32],
       [77, 81, 10],
       [83, 94,  4]])

In [ ]:
arr2

array([[97, 51, 57],
       [91, 18, 57],
       [61, 47, 18],
       [66, 62, 76],
       [54, 14,  5]])

In [ ]:
arr1 + arr2

array([[128,  95, 134],
       [104,  28, 129],
       [ 70,  93,  50],
       [143, 143,  86],
       [137, 108,   9]])

In [ ]:
arr2=np.random.randint(1,3,(5,1))
arr2
arr1=np.random.randint(1,3,(5,3))
arr1

array([[2, 2, 1],
       [2, 2, 2],
       [2, 1, 1],
       [1, 2, 2],
       [1, 1, 1]])

In [ ]:
arr1

array([[2, 2, 1],
       [2, 2, 2],
       [2, 1, 1],
       [1, 2, 2],
       [1, 1, 1]])

In [ ]:
arr2

array([[2],
       [1],
       [2],
       [2],
       [1]])

In [ ]:
arr1.shape

(5, 3)

In [ ]:
arr2.shape

(5, 1)

In [ ]:
arr1+arr2

array([[4, 4, 3],
       [3, 3, 3],
       [4, 3, 3],
       [3, 4, 4],
       [2, 2, 2]])

In [ ]:
arr2=np.random.randint(1,3,(7,1))
arr2
arr1=np.random.randint(1,3,(5,3))
arr1

array([[2, 2, 2],
       [1, 2, 1],
       [1, 1, 2],
       [1, 2, 1],
       [2, 2, 1]])

In [ ]:
arr1

array([[2, 2, 2],
       [1, 2, 1],
       [1, 1, 2],
       [1, 2, 1],
       [2, 2, 1]])

In [ ]:
arr2

array([[2],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2]])

In [ ]:
arr1.shape

(5, 3)

In [ ]:
arr2.shape

(7, 1)

In [ ]:
arr2=np.random.randint(1,3,(1,4))  
arr2
arr1=np.random.randint(1,3,(4,4))
arr1

array([[2, 2, 2, 2],
       [2, 2, 2, 1],
       [1, 2, 2, 2],
       [1, 2, 1, 2]])

In [ ]:
arr1

array([[2, 2, 2, 2],
       [2, 2, 2, 1],
       [1, 2, 2, 2],
       [1, 2, 1, 2]])

In [ ]:
arr2

array([[2, 2, 1, 2]])

In [ ]:
arr1.shape

(4, 4)

In [ ]:
arr2.shape

(1, 4)

In [ ]:
arr1+arr2    #rowwise

array([[4, 4, 3, 4],
       [4, 4, 3, 3],
       [3, 4, 3, 4],
       [3, 4, 2, 4]])

In [ ]:
arr1

array([[2, 2, 2, 2],
       [2, 2, 2, 1],
       [1, 2, 2, 2],
       [1, 2, 1, 2]])

In [ ]:
arr2

array([[2, 2, 1, 2]])

In [ ]:
arr2.T

array([[2],
       [2],
       [1],
       [2]])

In [ ]:
arr1+arr2.T #column wise

array([[4, 4, 4, 4],
       [4, 4, 4, 3],
       [2, 3, 3, 3],
       [3, 4, 3, 4]])

In [ ]:
arr1

array([[2, 2, 2, 2],
       [2, 2, 2, 1],
       [1, 2, 2, 2],
       [1, 2, 1, 2]])

In [ ]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.        , 1.41421356]])

In [ ]:
np.min(arr1)

1

In [ ]:
np.max(arr1)

2

In [ ]:
arr1.flatten()

array([2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2])

In [ ]:
np.mean(arr1)     #check

1.75

In [ ]:
np.median(arr1)       #check

2.0

In [ ]:
 import pandas as pd

In [ ]:
df=pd.DataFrame(arr1)  
df

   0  1  2  3
0  2  2  2  2
1  2  2  2  1
2  1  2  2  2
3  1  2  1  2

In [ ]:
df[0].mode()              #check

0    1
1    2
Name: 0, dtype: int32

In [ ]:
np.add(arr1,arr2)

array([[4, 4, 3, 4],
       [4, 4, 3, 3],
       [3, 4, 3, 4],
       [3, 4, 2, 4]])

In [ ]:
np.subtract(arr1,arr2)

array([[ 0,  0,  1,  0],
       [ 0,  0,  1, -1],
       [-1,  0,  1,  0],
       [-1,  0,  0,  0]])

In [ ]:
np.mod(arr1,arr2)          # check

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 0]])

In [ ]:
np.power(arr1,arr2)              # check

array([[4, 4, 2, 4],
       [4, 4, 2, 1],
       [1, 4, 2, 4],
       [1, 4, 1, 4]])

In [ ]:
arr1

array([[2, 2, 2, 2],
       [2, 2, 2, 1],
       [1, 2, 2, 2],
       [1, 2, 1, 2]])

In [ ]:
arr2

array([[2, 2, 1, 2]])

In [ ]:
arr1&arr2     # check all binary op.

array([[2, 2, 0, 2],
       [2, 2, 0, 0],
       [0, 2, 0, 2],
       [0, 2, 1, 2]])

In [ ]:
arr=np.array(["mohit","mahi"])
arr

array(['mohit', 'mahi'], dtype='<U5')

In [ ]:
np.char.lower(arr)

array(['mohit', 'mahi'], dtype='<U5')

In [ ]:
np.char.upper(arr)

array(['MOHIT', 'MAHI'], dtype='<U5')

In [ ]:
np.char.swapcase(arr)         #mtlb

array(['MOHIT', 'MAHI'], dtype='<U5')

In [ ]:
np.char.isalpha(arr)             #mtlb

array([ True,  True])

In [ ]:
arr=np.array([3,4,1,2,3,4,2,4,5,6,4,4,6,7])
arr

array([3, 4, 1, 2, 3, 4, 2, 4, 5, 6, 4, 4, 6, 7])

In [ ]:
np.sort(arr)

array([1, 2, 2, 3, 3, 4, 4, 4, 4, 4, 5, 6, 6, 7])

In [ ]:
np.sort(arr)[::-1]    #mtlb::

array([7, 6, 6, 5, 4, 4, 4, 4, 4, 3, 3, 2, 2, 1])

In [ ]:
arr=np.array([1,2,6,8,12,16])
arr

array([ 1,  2,  6,  8, 12, 16])

In [ ]:
np.searchsorted(arr,5)

2

In [ ]:
int(np.searchsorted(arr,5))

2

In [ ]:
np.append(arr,19)

array([ 1,  2,  6,  8, 12, 16, 19])

In [ ]:
arr

array([ 1,  2,  6,  8, 12, 16])

In [ ]:
np.insert(arr,int(np.searchsorted(arr,5)),5)

array([ 1,  2,  5,  6,  8, 12, 16])

In [ ]:
arr    #insert ke baad bhi 5 permanent save nhi hua

array([ 1,  2,  6,  8, 12, 16])

# 18 - 07 - 2025   check read

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\admin\.anaconda\anaconda4\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\.anaconda\anaconda4\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\.anaconda\anaconda4\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\.anaconda\anaconda4\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\.anaconda\anaconda4\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\admin\.anaconda\anaconda4\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
import pandas as pd

In [ ]:
l = [i for i in range(10)]
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
sr = pd.Series(l)
sr

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [ ]:
print(type(sr))

<class 'pandas.core.series.Series'>

In [ ]:
df= pd.DataFrame(l)
df

   0
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8
9  9

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
import numpy as np

In [ ]:
data1 = np.random.randint(1,100,10)
data1

array([38, 55, 23,  6, 21, 12, 91, 25, 65, 32])

In [ ]:
data2 = np.random.randint(1,100,10)
data2

array([71,  2, 43, 29, 36, 11, 72, 59, 49, 43])

In [ ]:
df = pd.DataFrame({'Maths':data1,
                   'Science':data2})
df

   Maths  Science
0     38       71
1     55        2
2     23       43
3      6       29
4     21       36
5     12       11
6     91       72
7     25       59
8     65       49
9     32       43

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df1 = pd.read_csv('https://raw.githubusercontent.com/PyDataWorkshop/datasets/refs/heads/master/bank-full.csv', delimiter=';')
df1

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [ ]:
type(df1)

pandas.core.frame.DataFrame

In [ ]:
df1['job']

0          management
1          technician
2        entrepreneur
3         blue-collar
4             unknown
             ...
45206      technician
45207         retired
45208         retired
45209     blue-collar
45210    entrepreneur
Name: job, Length: 45211, dtype: object

In [ ]:
df1.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [ ]:
df1[['job', 'education', 'default', 'balance', 'marital']]

                job  education default  balance   marital
0        management   tertiary      no     2143   married
1        technician  secondary      no       29    single
2      entrepreneur  secondary      no        2   married
3       blue-collar    unknown      no     1506   married
4           unknown    unknown      no        1    single
...             ...        ...     ...      ...       ...
45206    technician   tertiary      no      825   married
45207       retired    primary      no     1729  divorced
45208       retired  secondary      no     5715   married
45209   blue-collar  secondary      no      668   married
45210  entrepreneur  secondary      no     2971   married

[45211 rows x 5 columns]

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [ ]:
df.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
610,611,0,3,"Andersson, Mrs. Anders Johan (Alfrida Konstant...",female,39.0,1,5,347082,31.2750,NaN,S
703,704,0,3,"Gallagher, Mr. Martin",male,25.0,0,0,36864,7.7417,NaN,Q
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
87,88,0,3,"Slocovski, Mr. Selman Francis",male,NaN,0,0,SOTON/OQ 392086,8.0500,NaN,S
221,222,0,2,"Bracken, Mr. James H",male,27.0,0,0,220367,13.0000,NaN,S
771,772,0,3,"Jensen, Mr. Niels Peder",male,48.0,0,0,350047,7.8542,NaN,S
536,537,0,1,"Butt, Major. Archibald Willingham",male,45.0,0,0,113050,26.5500,B38,S
336,337,0,1,"Pears, Mr. Thomas Clinton",male,29.0,1,0,113776,66.6000,C2,S
602,603,0,1,"Harrington, Mr. Charles H",male,NaN,0,0,113796,42.4000,NaN,S
430,431,1,1,"Bjornstrom-Steffansson, Mr. Mauritz Hakan",male,28.0,0,0,110564,26.5500,C52,S

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df.to_csv('titanic.csv', index=False)

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df.shape

(891, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.describe(include='object')

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df.isnull().mean()*100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [ ]:
df.drop('Cabin', axis=1, inplace=True)

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [ ]:
# fillna
df['Age'].mean()

29.69911764705882

In [ ]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [ ]:
df['Age'].median()

28.0

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].median())

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
mode_freq = df['Embarked'].mode()[0]
mode_freq

'S'

In [ ]:
df['Embarked']=df['Embarked'].fillna(mode_freq)

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

# 19 - 07 - 2025 check and read

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.361582,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,13.019697,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
import numpy as np

In [ ]:
q1 =np.quantile(df['Age'], 0.25)
q1

22.0

In [ ]:
q2 =np.quantile(df['Age'], 0.5)
q2

28.0

In [ ]:
q3 =np.quantile(df['Age'], 0.75)
q3

35.0

In [ ]:
q4 =np.quantile(df['Age'], 1.0)
q4

80.0

In [ ]:
iqr = q3-q1
iqr

13.0

In [ ]:
lower = q1-1.5*iqr
lower

2.5

In [ ]:
upper = q3+1.5*iqr
upper

54.5

In [ ]:
df[(df['Age']>lower) & (df['Age']<upper)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
891-825

66

In [ ]:
# adding a column

df['new_col'] = 0

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,0

In [ ]:
df.drop('new_col', axis=1,inplace=True)

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
df[df['Age']>=18]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
len(df[(df['Age']<18) & (df['Survived']==0)])

52

In [ ]:
# show records of females who survived
df[(df["Sex"]=="female") & (df["Survived"]==1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C
...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S

In [ ]:
# show records of person who paid highest fare for traveling
df[df["Fare"]==df['Fare'].max()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,C

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [ ]:
# iloc and loc => intersecting data

df.iloc[0:3,0:3]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3

In [ ]:
df.iloc[0:3,['PassengerId', 'Survived', 'Pclass']]

IndexError: .iloc requires numeric indexers, got ['PassengerId' 'Survived' 'Pclass']

In [ ]:
df.loc[0:3,['PassengerId', 'Survived', 'Name']]

   PassengerId  Survived                                               Name
0            1         0                            Braund, Mr. Owen Harris
1            2         1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2            3         1                             Heikkinen, Miss. Laina
3            4         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)

In [ ]:
df_copy = df.set_index('Name')
df_copy

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
Name,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,S
"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,S
"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,28.0,1,2,W./C. 6607,23.4500,S
"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C
"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,Q

In [ ]:
df_copy.loc[0:3,['PassengerId', 'Survived', 'Age']]

TypeError: cannot do slice indexing on Index with these indexers [0] of type int

In [ ]:
df_copy.loc['Braund, Mr. Owen Harris',['PassengerId', 'Survived', 'Age']]

PassengerId       1
Survived          0
Age            22.0
Name: Braund, Mr. Owen Harris, dtype: object

In [ ]:
df_copy.iloc[0:3,0:3]

,PassengerId,Survived,Pclass
Name,,,
"Braund, Mr. Owen Harris",1,0,3
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1
"Heikkinen, Miss. Laina",3,1,3

In [ ]:
df_copy.reset_index()

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,S
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,28.0,1,2,W./C. 6607,23.4500,S
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,Q

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
# group by

df['Pclass']

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [ ]:
df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [ ]:
df.groupby('Pclass')['Fare'].sum().sort_values(ascending=False)

Pclass
1    18177.4125
3     6714.6951
2     3801.8417
Name: Fare, dtype: float64

In [ ]:
# max fare by Pclass
df.groupby('Pclass')['Fare'].max().sort_values(ascending=False)

Pclass
1    512.3292
2     73.5000
3     69.5500
Name: Fare, dtype: float64

In [ ]:
# min fare by Pclass
df.groupby('Pclass')['Fare'].min()

Pclass
1    0.0
2    0.0
3    0.0
Name: Fare, dtype: float64

In [ ]:
df.groupby('Pclass')['Fare'].mean().sort_values(ascending=False)

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [ ]:
df5 =df[['Parch', 'Ticket', 'Fare', 'Embarked']][:5]
df5

   Parch            Ticket     Fare Embarked
0      0         A/5 21171   7.2500        S
1      0          PC 17599  71.2833        C
2      0  STON/O2. 3101282   7.9250        S
3      0            113803  53.1000        S
4      0            373450   8.0500        S

In [ ]:
pd.concat([df1, df5])

,age,job,marital,education,default,balance,housing,loan,contact,day,...,duration,campaign,pdays,previous,poutcome,y,Parch,Ticket,Fare,Embarked
0,58.0,management,married,tertiary,no,2143.0,yes,no,unknown,5.0,...,261.0,1.0,-1.0,0.0,unknown,no,NaN,NaN,NaN,NaN
1,44.0,technician,single,secondary,no,29.0,yes,no,unknown,5.0,...,151.0,1.0,-1.0,0.0,unknown,no,NaN,NaN,NaN,NaN
2,33.0,entrepreneur,married,secondary,no,2.0,yes,yes,unknown,5.0,...,76.0,1.0,-1.0,0.0,unknown,no,NaN,NaN,NaN,NaN
3,47.0,blue-collar,married,unknown,no,1506.0,yes,no,unknown,5.0,...,92.0,1.0,-1.0,0.0,unknown,no,NaN,NaN,NaN,NaN
4,33.0,unknown,single,unknown,no,1.0,no,no,unknown,5.0,...,198.0,1.0,-1.0,0.0,unknown,no,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,A/5 21171,7.2500,S
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,PC 17599,71.2833,C
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,STON/O2. 3101282,7.9250,S
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,113803,53.1000,S
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,373450,8.0500,S

In [ ]:
# concat
df1 = df[['Name' , 'Survived', 'Pclass']][:5]
df1

                                                Name  Survived  Pclass
0                            Braund, Mr. Owen Harris         0       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1       1
2                             Heikkinen, Miss. Laina         1       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)         1       1
4                           Allen, Mr. William Henry         0       3

In [ ]:
df2 = df[['Name' , 'Survived', 'Pclass']][5:10]
df2

                                                Name  Survived  Pclass
5                                   Moran, Mr. James         0       3
6                            McCarthy, Mr. Timothy J         0       1
7                     Palsson, Master. Gosta Leonard         0       3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         1       3
9                Nasser, Mrs. Nicholas (Adele Achem)         1       2

In [ ]:
df2

                                                Name  Survived  Pclass
5                                   Moran, Mr. James         0       3
6                            McCarthy, Mr. Timothy J         0       1
7                     Palsson, Master. Gosta Leonard         0       3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         1       3
9                Nasser, Mrs. Nicholas (Adele Achem)         1       2

In [ ]:
df3=pd.concat([df1, df2])

In [ ]:
df3

                                                Name  Survived  Pclass
0                            Braund, Mr. Owen Harris         0       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1       1
2                             Heikkinen, Miss. Laina         1       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)         1       1
4                           Allen, Mr. William Henry         0       3
5                                   Moran, Mr. James         0       3
6                            McCarthy, Mr. Timothy J         0       1
7                     Palsson, Master. Gosta Leonard         0       3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         1       3
9                Nasser, Mrs. Nicholas (Adele Achem)         1       2

In [ ]:
df4=pd.concat([df1, df2], axis=1)
df4

,Name,Survived,Pclass,Name,Survived,Pclass
0,"Braund, Mr. Owen Harris",0.0,3.0,NaN,NaN,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1.0,1.0,NaN,NaN,NaN
2,"Heikkinen, Miss. Laina",1.0,3.0,NaN,NaN,NaN
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1.0,1.0,NaN,NaN,NaN
4,"Allen, Mr. William Henry",0.0,3.0,NaN,NaN,NaN
5,NaN,NaN,NaN,"Moran, Mr. James",0.0,3.0
6,NaN,NaN,NaN,"McCarthy, Mr. Timothy J",0.0,1.0
7,NaN,NaN,NaN,"Palsson, Master. Gosta Leonard",0.0,3.0
8,NaN,NaN,NaN,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",1.0,3.0
9,NaN,NaN,NaN,"Nasser, Mrs. Nicholas (Adele Achem)",1.0,2.0

In [ ]:
# merging
data1 = pd.DataFrame({'key1':[1,2,3,4,5],
                      'key2':[4,5,6,7,8],
                      'key3':[1,2,3,4,5],
                      })

In [ ]:
data2 = pd.DataFrame({'key1':[1,2,3,4,7],
                      'key4':[14,15,16,17,18],
                      'key5':[11,12,13,14,15],
                      })
data2

   key1  key4  key5
0     1    14    11
1     2    15    12
2     3    16    13
3     4    17    14
4     7    18    15

In [ ]:
pd.merge(data1, data2)

   key1  key2  key3  key4  key5
0     1     4     1    14    11
1     2     5     2    15    12
2     3     6     3    16    13
3     4     7     4    17    14

In [ ]:
data1 = pd.DataFrame({'key1':[1,2,3,4,5],
                      'key2':[4,5,6,7,8],
                      'key3':[1,2,3,4,5],
                      })
data1

   key1  key2  key3
0     1     4     1
1     2     5     2
2     3     6     3
3     4     7     4
4     5     8     5

In [ ]:
data2 = pd.DataFrame({'key1':[1,2,3,4,7],
                      'key2':[14,15,16,17,18],
                      'key5':[11,12,13,14,15],
                      })
data2

   key1  key2  key5
0     1    14    11
1     2    15    12
2     3    16    13
3     4    17    14
4     7    18    15

In [ ]:
pd.merge(data1,data2, on='key1')

   key1  key2_x  key3  key2_y  key5
0     1       4     1      14    11
1     2       5     2      15    12
2     3       6     3      16    13
3     4       7     4      17    14

In [ ]:
pd.merge(data1,data2, on='key1', how='inner')

   key1  key2_x  key3  key2_y  key5
0     1       4     1      14    11
1     2       5     2      15    12
2     3       6     3      16    13
3     4       7     4      17    14

# 21 - 07 - 2025 check n read

In [ ]:
# apply
df['Fare_INR']= df['Fare'].apply(lambda x:x*100)

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Fare_INR
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,725.00
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,7128.33
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,792.50
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,5310.00
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,805.00
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,1300.00
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,3000.00
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S,2345.00
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,3000.00
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,775.00

In [ ]:
def euro_to_inr(x):
  return x*100

df['Fare_INR_user_func']= df['Fare'].apply(euro_to_inr)

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Fare_INR,Fare_INR_user_func
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,725.00,725.00
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,7128.33,7128.33
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,792.50,792.50
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,5310.00,5310.00
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,805.00,805.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,1300.00,1300.00
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,3000.00,3000.00
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S,2345.00,2345.00
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,3000.00,3000.00
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,775.00,775.00

In [ ]:
def new_fare(r):
  if r['Age'] <18:
    return r['Fare']/2
  else:
    return r['Fare']

df['Updated_Fare']= df.apply(new_fare,axis=1)

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Fare_INR,Fare_INR_user_func,Updated_Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,725.00,725.00,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,7128.33,7128.33,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,792.50,792.50,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,5310.00,5310.00,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,805.00,805.00,8.0500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,1300.00,1300.00,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,3000.00,3000.00,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S,2345.00,2345.00,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,3000.00,3000.00,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,775.00,775.00,7.7500

In [ ]:
df[df['Age']<18]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Fare_INR,Fare_INR_user_func,Updated_Fare
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,S,2107.50,2107.50,10.53750
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C,3007.08,3007.08,15.03540
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,S,1670.00,1670.00,8.35000
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,S,785.42,785.42,3.92710
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,Q,2912.50,2912.50,14.56250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
850,851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.0,4,2,347082,31.2750,S,3127.50,3127.50,15.63750
852,853,0,3,"Boulos, Miss. Nourelain",female,9.0,1,1,2678,15.2458,C,1524.58,1524.58,7.62290
853,854,1,1,"Lines, Miss. Mary Conover",female,16.0,0,1,PC 17592,39.4000,S,3940.00,3940.00,19.70000
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,S,1113.33,1113.33,5.56665
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,C,722.50,722.50,3.61250

In [ ]:
# give the insurance money to the people who died in titanic incident the insured money is 5 times of the ticket purchased?

In [ ]:
#sorting

df['Pclass'].sort_values(ascending=False)

0      3
511    3
500    3
501    3
502    3
      ..
102    1
710    1
711    1
712    1
445    1
Name: Pclass, Length: 891, dtype: int64

In [ ]:
df.sort_values('Pclass', ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Fare_INR,Fare_INR_user_func,Updated_Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,725.00,725.00,7.25000
511,512,0,3,"Webber, Mr. James",male,28.0,0,0,SOTON/OQ 3101316,8.0500,S,805.00,805.00,8.05000
500,501,0,3,"Calic, Mr. Petar",male,17.0,0,0,315086,8.6625,S,866.25,866.25,4.33125
501,502,0,3,"Canavan, Miss. Mary",female,21.0,0,0,364846,7.7500,Q,775.00,775.00,7.75000
502,503,0,3,"O'Sullivan, Miss. Bridget Mary",female,28.0,0,0,330909,7.6292,Q,762.92,762.92,7.62920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,103,0,1,"White, Mr. Richard Frasar",male,21.0,0,1,35281,77.2875,S,7728.75,7728.75,77.28750
710,711,1,1,"Mayne, Mlle. Berthe Antonine (""Mrs de Villiers"")",female,24.0,0,0,PC 17482,49.5042,C,4950.42,4950.42,49.50420
711,712,0,1,"Klaber, Mr. Herman",male,28.0,0,0,113028,26.5500,S,2655.00,2655.00,26.55000
712,713,1,1,"Taylor, Mr. Elmer Zebley",male,48.0,1,0,19996,52.0000,S,5200.00,5200.00,52.00000
445,446,1,1,"Dodge, Master. Washington",male,4.0,0,2,33638,81.8583,S,8185.83,8185.83,40.92915

In [ ]:
df.sort_index( ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Fare_INR,Fare_INR_user_func,Updated_Fare
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,775.00,775.00,7.7500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,3000.00,3000.00,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S,2345.00,2345.00,23.4500
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,3000.00,3000.00,30.0000
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,1300.00,1300.00,13.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,805.00,805.00,8.0500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,5310.00,5310.00,53.1000
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,792.50,792.50,7.9250
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,7128.33,7128.33,71.2833
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,725.00,725.00,7.2500

In [ ]:
df3 = pd.DataFrame({'Desc':['''Fast X is a 2023 American action film directed by Louis Leterrier from a screenplay written by Dan Mazeau and Justin Lin, both of whom also co-wrote the story with Zach Dean. The sequel to F9 (2021), it is the tenth main installment and the eleventh installment overall in the Fast & Furious franchise. It stars Vin Diesel as Dominic Toretto, alongside Michelle Rodriguez, Tyrese Gibson, Chris "Ludacris" Bridges, John Cena, Nathalie Emmanuel, Jordana Brewster, Sung Kang, Scott Eastwood, Daniela Melchior, Alan Ritchson, Helen Mirren, Brie Larson, Rita Moreno, Jason Statham, Jason Momoa, and Charlize Theron. In the film, Toretto must protect his family from Dante Reyes (Momoa), who pursues revenge for his father's death and the loss of their fortune.

Development on a tenth main Fast & Furious film began by October 2020, with Lin returning to direct. The film's official title was revealed when principal photography began in April 2022. Lin left as director later that month, citing creative differences, though he retained writing and producing credits. Leterrier was then hired as his replacement a week later and performed several uncredited rewrites to the screenplay. Longtime franchise composer Brian Tyler returned to score the film. With an estimated net production budget of $378.8 million, Fast X is the fourth-most expensive film ever made. Filming lasted until that August, taking place in London, Rome, Turin, Lisbon, and Los Angeles.

Fast X premiered in Rome on May 12, 2023, and was released in the United States on May 19, by Universal Pictures. The film received mixed reviews from critics, with praise for its action sequences and Momoa's performance but criticism towards the writing. It grossed $714 million worldwide, becoming the fifth-highest-grossing film of 2023. A sequel that reportedly serves as the final main installment is in development and is scheduled to be released in April 2027.''']})

In [ ]:
df3

                                                Desc
0  Fast X is a 2023 American action film directed...

In [ ]:
pd.set_option('display.max_colwidth',10000)

In [ ]:
df3 = pd.DataFrame({'Desc':['''Fast X is a 2023 American action film directed by Louis Leterrier from a screenplay written by Dan Mazeau and Justin Lin, both of whom also co-wrote the story with Zach Dean. The sequel to F9 (2021), it is the tenth main installment and the eleventh installment overall in the Fast & Furious franchise. It stars Vin Diesel as Dominic Toretto, alongside Michelle Rodriguez, Tyrese Gibson, Chris "Ludacris" Bridges, John Cena, Nathalie Emmanuel, Jordana Brewster, Sung Kang, Scott Eastwood, Daniela Melchior, Alan Ritchson, Helen Mirren, Brie Larson, Rita Moreno, Jason Statham, Jason Momoa, and Charlize Theron. In the film, Toretto must protect his family from Dante Reyes (Momoa), who pursues revenge for his father's death and the loss of their fortune.

Development on a tenth main Fast & Furious film began by October 2020, with Lin returning to direct. The film's official title was revealed when principal photography began in April 2022. Lin left as director later that month, citing creative differences, though he retained writing and producing credits. Leterrier was then hired as his replacement a week later and performed several uncredited rewrites to the screenplay. Longtime franchise composer Brian Tyler returned to score the film. With an estimated net production budget of $378.8 million, Fast X is the fourth-most expensive film ever made. Filming lasted until that August, taking place in London, Rome, Turin, Lisbon, and Los Angeles.

Fast X premiered in Rome on May 12, 2023, and was released in the United States on May 19, by Universal Pictures. The film received mixed reviews from critics, with praise for its action sequences and Momoa's performance but criticism towards the writing. It grossed $714 million worldwide, becoming the fifth-highest-grossing film of 2023. A sequel that reportedly serves as the final main installment is in development and is scheduled to be released in April 2027.''']})

df3

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Desc
0  Fast X is a 2023 American action film directed by Louis Leterrier from a screenplay written by Dan Mazeau and Justin Lin, both of whom also co-wrote the story with Zach Dean. The sequel to F9 (2021), it is the tenth main installment and the eleventh installment overall in the Fast & Furious franchise. It stars Vin Diesel as Dominic Toretto, alongside Michelle Rodriguez, Tyrese Gibson, Chris "Ludacris" Bridges, John Cena, Nathalie Emmanuel, Jordana Brewster, Sung Kang, Scott Eastwood, Daniela Melchior, Alan Ritchson, Helen Mirren, Brie Larson, Rita Moreno, Jason Statham, Jason Momoa, and Charlize Theron. In the film, Toretto must protect his family from Dante Reyes (Momoa), who pursues revenge for his father's death and the loss of their fortune.\n\nDevelopment on a tenth main Fast & Furious film began by October 2020, with Lin returning to direct. The film's official title was revealed when principal photography began in April 2022. Lin left as director later that month, citing creative differences, though he retained writing and producing credits. Leterrier was then hired as his replacement a week later and performed several uncredited rewrites to the screenplay. Longtime franchise composer Brian Tyler returned to score the film. With an estimated net production budget of $378.8 million, Fast X is the fourth-most expensive film ever made. Filming lasted until that August, taking place in London, Rome, Turin, Lisbon, and Los Angeles.\n\nFast X premiered in Rome on May 12, 2023, and was released in the United States on May 19, by Universal Pictures. The film received mixed reviews from critics, with praise for its action sequences and Momoa's performance but criticism towards the writing. It grossed $714 million worldwide, becoming the fifth-highest-grossing film of 2023. A sequel that reportedly serves as the final main installment is in development and is scheduled to be released in April 2027.

In [ ]:
# windowing functions

df4 = pd.DataFrame({'a':[3,4,5,2,1,3,4,5,5]})

df4

   a
0  3
1  4
2  5
3  2
4  1
5  3
6  4
7  5
8  5

In [ ]:
df4['a'].rolling(window=2).sum()

0     NaN
1     7.0
2     9.0
3     7.0
4     3.0
5     4.0
6     7.0
7     9.0
8    10.0
Name: a, dtype: float64

In [ ]:
df4['a'].rolling(window=3).sum()

0     NaN
1     NaN
2    12.0
3    11.0
4     8.0
5     6.0
6     8.0
7    12.0
8    14.0
Name: a, dtype: float64

In [ ]:
df4['a'].rolling(window=3).apply(lambda x: x[0]*x[1], raw=True)

0     NaN
1     NaN
2    12.0
3    20.0
4    10.0
5     2.0
6     3.0
7    12.0
8    20.0
Name: a, dtype: float64

In [ ]:
def mult(x):
  res = 1
  for i in x:
    res *= i
  return res

df4['result'] = df4['a'].rolling(window=6).apply(mult, raw=True)
df4

   a  result
0  3     NaN
1  4     NaN
2  5     NaN
3  2     NaN
4  1     NaN
5  3   360.0
6  4   480.0
7  5   600.0
8  5   600.0

In [ ]:
date=pd.date_range(start = "2025-05-01", end='2025-05-31')
date

DatetimeIndex(['2025-05-01', '2025-05-02', '2025-05-03', '2025-05-04',
               '2025-05-05', '2025-05-06', '2025-05-07', '2025-05-08',
               '2025-05-09', '2025-05-10', '2025-05-11', '2025-05-12',
               '2025-05-13', '2025-05-14', '2025-05-15', '2025-05-16',
               '2025-05-17', '2025-05-18', '2025-05-19', '2025-05-20',
               '2025-05-21', '2025-05-22', '2025-05-23', '2025-05-24',
               '2025-05-25', '2025-05-26', '2025-05-27', '2025-05-28',
               '2025-05-29', '2025-05-30', '2025-05-31'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
date_str = ['2025-05-01', '2025-05-02', '2025-05-03', '2025-05-04',
               '2025-05-05', '2025-05-06', '2025-05-07', '2025-05-08',
               '2025-05-09', '2025-05-10', '2025-05-11', '2025-05-12',
               '2025-05-13', '2025-05-14', '2025-05-15', '2025-05-16',
               '2025-05-17', '2025-05-18', '2025-05-19', '2025-05-20',
               '2025-05-21', '2025-05-22', '2025-05-23', '2025-05-24',
               '2025-05-25', '2025-05-26', '2025-05-27', '2025-05-28',
               '2025-05-29', '2025-05-30', '2025-05-31']

In [ ]:
date_str

['2025-05-01',
 '2025-05-02',
 '2025-05-03',
 '2025-05-04',
 '2025-05-05',
 '2025-05-06',
 '2025-05-07',
 '2025-05-08',
 '2025-05-09',
 '2025-05-10',
 '2025-05-11',
 '2025-05-12',
 '2025-05-13',
 '2025-05-14',
 '2025-05-15',
 '2025-05-16',
 '2025-05-17',
 '2025-05-18',
 '2025-05-19',
 '2025-05-20',
 '2025-05-21',
 '2025-05-22',
 '2025-05-23',
 '2025-05-24',
 '2025-05-25',
 '2025-05-26',
 '2025-05-27',
 '2025-05-28',
 '2025-05-29',
 '2025-05-30',
 '2025-05-31']

In [ ]:
date

DatetimeIndex(['2025-05-01', '2025-05-02', '2025-05-03', '2025-05-04',
               '2025-05-05', '2025-05-06', '2025-05-07', '2025-05-08',
               '2025-05-09', '2025-05-10', '2025-05-11', '2025-05-12',
               '2025-05-13', '2025-05-14', '2025-05-15', '2025-05-16',
               '2025-05-17', '2025-05-18', '2025-05-19', '2025-05-20',
               '2025-05-21', '2025-05-22', '2025-05-23', '2025-05-24',
               '2025-05-25', '2025-05-26', '2025-05-27', '2025-05-28',
               '2025-05-29', '2025-05-30', '2025-05-31'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df_date = pd.DataFrame({"date":date,
                        "date_str":date_str})

In [ ]:
df_date

         date    date_str
0  2025-05-01  2025-05-01
1  2025-05-02  2025-05-02
2  2025-05-03  2025-05-03
3  2025-05-04  2025-05-04
4  2025-05-05  2025-05-05
5  2025-05-06  2025-05-06
6  2025-05-07  2025-05-07
7  2025-05-08  2025-05-08
8  2025-05-09  2025-05-09
9  2025-05-10  2025-05-10
10 2025-05-11  2025-05-11
11 2025-05-12  2025-05-12
12 2025-05-13  2025-05-13
13 2025-05-14  2025-05-14
14 2025-05-15  2025-05-15
15 2025-05-16  2025-05-16
16 2025-05-17  2025-05-17
17 2025-05-18  2025-05-18
18 2025-05-19  2025-05-19
19 2025-05-20  2025-05-20
20 2025-05-21  2025-05-21
21 2025-05-22  2025-05-22
22 2025-05-23  2025-05-23
23 2025-05-24  2025-05-24
24 2025-05-25  2025-05-25
25 2025-05-26  2025-05-26
26 2025-05-27  2025-05-27
27 2025-05-28  2025-05-28
28 2025-05-29  2025-05-29
29 2025-05-30  2025-05-30
30 2025-05-31  2025-05-31

In [ ]:
df_date['date'].dt.month

0     5
1     5
2     5
3     5
4     5
5     5
6     5
7     5
8     5
9     5
10    5
11    5
12    5
13    5
14    5
15    5
16    5
17    5
18    5
19    5
20    5
21    5
22    5
23    5
24    5
25    5
26    5
27    5
28    5
29    5
30    5
Name: date, dtype: int32

In [ ]:
df_date['date_str'].dt.month

AttributeError: Can only use .dt accessor with datetimelike values

In [ ]:
df_date['Updated Date'] = pd.to_datetime(df_date['date_str'])

In [ ]:
df_date

         date    date_str Updated Date
0  2025-05-01  2025-05-01   2025-05-01
1  2025-05-02  2025-05-02   2025-05-02
2  2025-05-03  2025-05-03   2025-05-03
3  2025-05-04  2025-05-04   2025-05-04
4  2025-05-05  2025-05-05   2025-05-05
5  2025-05-06  2025-05-06   2025-05-06
6  2025-05-07  2025-05-07   2025-05-07
7  2025-05-08  2025-05-08   2025-05-08
8  2025-05-09  2025-05-09   2025-05-09
9  2025-05-10  2025-05-10   2025-05-10
10 2025-05-11  2025-05-11   2025-05-11
11 2025-05-12  2025-05-12   2025-05-12
12 2025-05-13  2025-05-13   2025-05-13
13 2025-05-14  2025-05-14   2025-05-14
14 2025-05-15  2025-05-15   2025-05-15
15 2025-05-16  2025-05-16   2025-05-16
16 2025-05-17  2025-05-17   2025-05-17
17 2025-05-18  2025-05-18   2025-05-18
18 2025-05-19  2025-05-19   2025-05-19
19 2025-05-20  2025-05-20   2025-05-20
20 2025-05-21  2025-05-21   2025-05-21
21 2025-05-22  2025-05-22   2025-05-22
22 2025-05-23  2025-05-23   2025-05-23
23 2025-05-24  2025-05-24   2025-05-24
24 2025-05-25  2025-05-25   2025-05-25
25 2025-05-26  2025-05-26   2025-05-26
26 2025-05-27  2025-05-27   2025-05-27
27 2025-05-28  2025-05-28   2025-05-28
28 2025-05-29  2025-05-29   2025-05-29
29 2025-05-30  2025-05-30   2025-05-30
30 2025-05-31  2025-05-31   2025-05-31

In [ ]:
df_date.dtypes

date            datetime64[ns]
date_str                object
Updated Date    datetime64[ns]
dtype: object

# 22 - 07 - 2025